---

- name: Restart and enable zabbix-agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
    enabled: true

- name: Restart and enable zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: true
